# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package
on:
  push:
    branches: ['master', 'beta']

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: git config
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

      - name: setup semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

#      - name: Get the version
#        id: get_version
#        run: echo ::set-output name=VERSION::${$(git describe --abbrev=0 --tags)/v/}

#      - name: substring-action
#        uses: bhowell2/github-substring-action@v1.0.0
#        id: get_version
#        with:
#          value: $(git describe --abbrev=0 --tags)
#          index_of_str: "v"          # ${{ steps.get_version.outputs.substring }}

      - name: Get tag
        id: get_version
        uses: dawidd6/action-get-tag@v1.1.0
        with:
            strip_v: true

      - run: echo ${{ steps.tag.outputs.tag }}

      - name: Set version
        run : mvn versions:set -DnewVersion=${{ steps.tag.outputs.tag }}

#      - name: Set version
#        run : mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}
#
#      - name: tag number
#        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}
#
#      - name: Get latest release version number
#        id: get_version
#        uses: battila7/get-version-action@v2
#
#      - name: Set version
#        run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.version }}
#
#      - name: Build with Maven
#        run: mvn -B package

      - name: Publish to GitHub Packages  Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}